name: Prophet Tests

# CINTENT >> MANUAL TRIGGER
# on: [push, pull_request]
on: [repository_dispatch, workflow_dispatch]

jobs:
  test:
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ['3.11']
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    # CINTENT >> INSERT_CINTENT
    - uses: JavidDitty/setup-cintent@main
      with:
        profiler: "setprofile"

    - name: Install other dependencies
      run: |
        pip install . \
          -r requirements/requirements-test.txt \
          -r requirements/requirements-extras-prophet.txt

    - name: Test with pytest
      run: |
        pytest -n2 --doctest-modules test/ext/prophet

    # CINTENT >> INSERT_CINTENT
    - name: Upload CIntent Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ env.CINTENT_ARTIFACT_NAME }}
        path: ${{ env.CINTENT_LOGS }}
